name: Check schemas

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify schemas up-to-date
        run: |
          sh generate_schemas.sh

          if [ -n "$(git status --porcelain)" ]; then
            echo "::error:: Uncommited schema changesa. Please run 'sh generate_schemas.sh' locally and commit the changes."
            exit 1
          fi
